# Generated by Django 5.2.1 on 2025-08-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
